### PR TITLE
Adding custom message and ability to disable rate-limiting message

### PR DESCRIPTION
**Pull request by TobiTenno**
@michaelansel @geoffreyanderson please review my submission

### CODE REVIEW

**Comment by michaelansel** [comment]
Sorry for the delay on this! I completely missed the notification and just happened to stumble across it today :sweat: 

Could you clean up the merge conflict and rebase it on top of #10? I'd like to use #10 for the suppression variable and then this for the custom message. Can you also add documentation to the README for the new environment variable?

**Comment by TobiTenno** [comment]
Merge conflict fixed, i'll just wait until #10 is merged and i'll rebase it on top of there.

**Comment by aliasfalse** [comment]
@michaelansel i can pull #10's changes in, it doesn't look like @ehammersly has been on in a while. that way the changes can get in

**Comment by TobiTenno** [comment]
actually, i'm legitimately confused now... i think the changes from #10 and #11 are the same, #11 just has a different env variable name for the disable variable and also has the message... why not just take #11?

**Comment by TobiTenno** [comment]
@michaelansel so you just want the custom message formatting for this one and for me to remove the suppression variable?

**Comment by TobiTenno** [comment]
moving to new PR

**Pull request closed without merging**
